version: "3"

services:
  db:
    image: postgres:16
    container_name: postgres
    volumes:
      - ~/.pg/pg_data/user:/var/lib/postgresql/data
    env_file:
      - .env
  Gas:
    image: backend
    container_name: backend
    depends_on:
      - db
    volumes:
      - media:/media
    env_file:
      - .env
    ports:
      - "8080:8000"


volumes:
  media:
