# Generated by Django 5.0.1 on 2024-01-23 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_brands_table_alter_cars_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.customuser', verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cars',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.brands', verbose_name='Бренд автомобиля'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Модель автомобиля'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='registration_number',
            field=models.CharField(max_length=6, verbose_name='Регистрационный номер'),
        ),
    ]
