# Generated by Django 5.0.1 on 2024-01-23 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fueling',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='storepurchases',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
