# Generated by Django 5.0.1 on 2024-02-26 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_fueling_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fueling',
            name='car',
        ),
        migrations.RemoveField(
            model_name='fuelcolumns',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='fueling',
            name='column_number',
        ),
        migrations.RemoveField(
            model_name='fueling',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='storepurchases',
            name='product',
        ),
        migrations.DeleteModel(
            name='Brands',
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
        migrations.DeleteModel(
            name='FuelColumns',
        ),
        migrations.DeleteModel(
            name='Fueling',
        ),
        migrations.DeleteModel(
            name='FuelTypes',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='StorePurchases',
        ),
    ]
