# Generated by Django 5.0.1 on 2024-03-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_cart_cartitem_cart_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefuelingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('refueling_date_time', models.DateTimeField()),
                ('fuel_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
