# Generated by Django 5.0.1 on 2024-03-26 16:29

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_refuelinghistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=backend.models.product_image_path),
        ),
    ]
