# Generated by Django 5.0.1 on 2024-03-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_remove_cartitem_cart_remove_cartitem_product_basket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketproduct',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
