# Generated by Django 5.0.1 on 2024-04-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_fuelstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='longitude',
            field=models.FloatField(default=5.1),
            preserve_default=False,
        ),
    ]
