# Generated by Django 5.0.1 on 2024-04-06 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_fuelstation_latitude_fuelstation_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('octane_number', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fuelstation',
            name='datetime',
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='fuel_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RemoveField(
            model_name='fuelstation',
            name='fuel_type',
        ),
        migrations.CreateModel(
            name='FuelColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('fuel_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fuel_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='backend.fuelstation')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.fueltype')),
            ],
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='fuel_type',
            field=models.ManyToManyField(related_name='fuel_stations', through='backend.FuelColumn', to='backend.fueltype'),
        ),
    ]
