# Generated by Django 5.0.1 on 2024-04-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_fueltype_remove_fuelstation_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcolumn',
            name='price_per_liter',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
