# Generated by Django 5.0.1 on 2024-04-08 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
