# Generated by Django 5.0.1 on 2024-04-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_remove_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_tank_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
