# Generated by Django 5.0.1 on 2024-04-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_rename_name_refuelinghistory_refueling_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refuelinghistory',
            name='refueling_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
