# Generated by Django 5.0.1 on 2024-04-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_alter_refuelinghistory_refueling_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='refuelinghistory',
            name='fuel_cost',
            field=models.DecimalField(decimal_places=2, default=13, max_digits=10),
            preserve_default=False,
        ),
    ]
