# Generated by Django 5.0.1 on 2024-04-18 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_refuelinghistory_fuel_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refuelinghistory',
            name='refueling_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.fuelstation'),
        ),
    ]
