# Generated by Django 5.0.1 on 2024-04-27 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_purchase_purchase_qwe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_qwe',
        ),
    ]
