# Generated by Django 5.0.1 on 2024-04-28 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_remove_purchase_product_remove_purchase_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='products',
        ),
    ]
