# Generated by Django 5.0.1 on 2024-04-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_remove_purchase_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='products',
            field=models.ManyToManyField(through='backend.PurchaseItem', to='backend.product'),
        ),
    ]
