# Generated by Django 5.0.1 on 2024-02-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(db_index=True, default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(db_index=True, default=2, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
