# Generated by Django 5.0.1 on 2024-02-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_alter_user_firstname_alter_user_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_at',
            new_name='created_aat',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='emaila',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='firstaname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='is_actaive',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_stafaf',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='lastaname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updated_at',
            new_name='updated_aat',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='useraname',
        ),
    ]
