# Generated by Django 5.0.1 on 2024-02-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_rename_created_at_user_created_aat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emaila',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='firstaname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_actaive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_stafaf',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastaname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='useraname',
            new_name='username',
        ),
    ]
