# Generated by Django 5.0.1 on 2024-02-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_rename_emaila_user_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_aat',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updated_aat',
            new_name='updated_at',
        ),
    ]
